# error: default=None, else "stuff", "form", "crc", "ack"
# type: default="data", else "remote"
# bus_idle: default=0, else lenght of bus idle period
Frames:
  - id: 0x777 # standard frame
    dlc: 2
    error: "stuff"
    data:
    - 0xe7
    - 0x83
  - id: 0x123 # standard frame
    dlc: 2
    error:
    data:
    - 0xaf
    - 0xfe
  - id: 0x125 # standard frame
    dlc: 2
    error:
    data:
    - 0xbe
    - 0xef
  - id: 0x127 # standard frame
    dlc: 2
    error:
    data:
    - 0xde
    - 0xad
  - id: 0x18 # standard frame
    dlc: 2
    error:
    data:
    - 0xde
    - 0xad
  - id: 0x15 # standard frame
    dlc: 2
    error:
    data:
    - 0xde
    - 0xad
    - 0xbe
    - 0xef