# error: default=None, else "stuff", "form", "crc", "ack"
# type: default="data", else "remote"
# bus_idle: default=0, else lenght of bus idle period
Frames:
  - id: 0x777 # standard frame
    dlc: 2
    #error: "stuff"
    data:
    - 0xe7
    - 0x83
#  - id: 0x999 # extended frame
#    dlc: 1
#    data:
#    - 0xfb
#  - id: 0x111 # standard frame
#    dlc: 5
#    data:
#    - 0x6d
#    - 0x40
#    - 0xfb
#    - 0xfc
#    - 0x64