# error: default=None, else "stuff", "form", "crc", "ack"
# type: default="data", else "remote"
# bus_idle: default=0, else lenght of bus idle period
Frames:
  - id: 0x777 # standard frame
    dlc: 1
    error:
    data:
    - 0x11
  - id: 0x123 # standard frame
    dlc: 2
    error:
    data:
    - 0x11
    - 0x22
  - id: 0x125 # standard frame
    dlc: 5
    error:
    data:
    - 0x11
    - 0x22
    - 0x33
    - 0x44
    - 0x55

  - id: 0x125 # standard frame
    dlc: 8
    error:
    data:
    - 0x11
    - 0x22
    - 0x33
    - 0x44
    - 0x55
    - 0x66
    - 0x77
    - 0x88
